/**
	This file is part of adapt-through.

    Adapt-through is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Adapt-through is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Adapt-through.  If not, see <http://www.gnu.org/licenses/>.
*/
package br.com.ziben.model;

// Generated Oct 30, 2013 12:33:40 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbAnaliseCreditoComplFncl generated by hbm2java
 */
@Entity
@Table(name = "tb_analise_credito_compl_fncl", schema = "public")
public class TbAnaliseCreditoComplFncl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5812067525166423432L;
	
	private TbAnaliseCreditoComplFnclId id;

	public TbAnaliseCreditoComplFncl() {
	}

	public TbAnaliseCreditoComplFncl(TbAnaliseCreditoComplFnclId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codfil", column = @Column(name = "codfil", precision = 3, scale = 0)),
			@AttributeOverride(name = "idanalise", column = @Column(name = "idanalise", precision = 9, scale = 0)),
			@AttributeOverride(name = "dtultmov", column = @Column(name = "dtultmov", length = 29)),
			@AttributeOverride(name = "hrultmov", column = @Column(name = "hrultmov", length = 29)),
			@AttributeOverride(name = "creditApplicationCod", column = @Column(name = "credit_application_cod", length = 15)),
			@AttributeOverride(name = "xmllog", column = @Column(name = "xmllog", length = 2000)),
			@AttributeOverride(name = "mensagem1", column = @Column(name = "mensagem1", length = 300)),
			@AttributeOverride(name = "mensagem2", column = @Column(name = "mensagem2", length = 300)) })
	public TbAnaliseCreditoComplFnclId getId() {
		return this.id;
	}

	public void setId(TbAnaliseCreditoComplFnclId id) {
		this.id = id;
	}

}
