package br.com.ziben.model;

// Generated Oct 30, 2013 4:54:18 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.PersistenceUnit;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAnaliseCreditoFncl generated by hbm2java
 */
@Entity
@PersistenceUnit(unitName = "dbZema")
@Table(name = "TB_ANALISE_CREDITO_FNCL", schema = "dbo", catalog = "dbZema")
public class TbAnaliseCreditoFncl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1903212818103677245L;

	private TbAnaliseCreditoFnclId id;
	private Boolean tipoped;
	private Long numpedven;
	private Date dtultmov;
	private Date hrultmov;
	private Short status;
	private Date dtlancto;
	private String segUsuarioCpf;
	private String mensagem1;
	private String mensagem2;
	private long codcli;
	private BigDecimal valor;
	private Short statusEnvio;
	private Clob detalhes;
	private Date dtinclusao;
	private Date hrinclusao;
	private Date dtinclusaoFilial;
	private Date hrinclusaoFilial;
	private Date dtanalise;
	private Date hranalise;
	private Long idPedidoCartao;
	private String nomcli;
	private Long cgccpf;
	private String xmllog;
	private String condpgto;

	public TbAnaliseCreditoFncl() {
	}

	public TbAnaliseCreditoFncl(TbAnaliseCreditoFnclId id, Date dtultmov, Date hrultmov, Date dtlancto, String segUsuarioCpf, long codcli) {
		this.id = id;
		this.dtultmov = dtultmov;
		this.hrultmov = hrultmov;
		this.dtlancto = dtlancto;
		this.segUsuarioCpf = segUsuarioCpf;
		this.codcli = codcli;
	}

	public TbAnaliseCreditoFncl(TbAnaliseCreditoFnclId id, Boolean tipoped, Long numpedven, Date dtultmov, Date hrultmov, Short status, Date dtlancto,
			String segUsuarioCpf, String mensagem1, String mensagem2, long codcli, BigDecimal valor, Short statusEnvio, Clob detalhes, Date dtinclusao, Date hrinclusao,
			Date dtinclusaoFilial, Date hrinclusaoFilial, Date dtanalise, Date hranalise, Long idPedidoCartao, String nomcli, Long cgccpf, String xmllog, String condpgto) {
		this.id = id;
		this.tipoped = tipoped;
		this.numpedven = numpedven;
		this.dtultmov = dtultmov;
		this.hrultmov = hrultmov;
		this.status = status;
		this.dtlancto = dtlancto;
		this.segUsuarioCpf = segUsuarioCpf;
		this.mensagem1 = mensagem1;
		this.mensagem2 = mensagem2;
		this.codcli = codcli;
		this.valor = valor;
		this.statusEnvio = statusEnvio;
		this.detalhes = detalhes;
		this.dtinclusao = dtinclusao;
		this.hrinclusao = hrinclusao;
		this.dtinclusaoFilial = dtinclusaoFilial;
		this.hrinclusaoFilial = hrinclusaoFilial;
		this.dtanalise = dtanalise;
		this.hranalise = hranalise;
		this.idPedidoCartao = idPedidoCartao;
		this.nomcli = nomcli;
		this.cgccpf = cgccpf;
		this.xmllog = xmllog;
		this.condpgto = condpgto;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codfil", column = @Column(name = "CODFIL", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "idanalise", column = @Column(name = "IDANALISE", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "idproduto", column = @Column(name = "IDPRODUTO", nullable = false, precision = 3, scale = 0)) })
	public TbAnaliseCreditoFnclId getId() {
		return this.id;
	}

	public void setId(TbAnaliseCreditoFnclId id) {
		this.id = id;
	}

	@Column(name = "TIPOPED", precision = 1, scale = 0)
	public Boolean getTipoped() {
		return this.tipoped;
	}

	public void setTipoped(Boolean tipoped) {
		this.tipoped = tipoped;
	}

	@Column(name = "NUMPEDVEN", precision = 12, scale = 0)
	public Long getNumpedven() {
		return this.numpedven;
	}

	public void setNumpedven(Long numpedven) {
		this.numpedven = numpedven;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTULTMOV", nullable = false, length = 23)
	public Date getDtultmov() {
		return this.dtultmov;
	}

	public void setDtultmov(Date dtultmov) {
		this.dtultmov = dtultmov;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRULTMOV", nullable = false, length = 23)
	public Date getHrultmov() {
		return this.hrultmov;
	}

	public void setHrultmov(Date hrultmov) {
		this.hrultmov = hrultmov;
	}

	@Column(name = "STATUS", precision = 3, scale = 0)
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTLANCTO", nullable = false, length = 23)
	public Date getDtlancto() {
		return this.dtlancto;
	}

	public void setDtlancto(Date dtlancto) {
		this.dtlancto = dtlancto;
	}

	@Column(name = "SEG_USUARIO_CPF", nullable = false, length = 11)
	public String getSegUsuarioCpf() {
		return this.segUsuarioCpf;
	}

	public void setSegUsuarioCpf(String segUsuarioCpf) {
		this.segUsuarioCpf = segUsuarioCpf;
	}

	@Column(name = "MENSAGEM1", length = 300)
	public String getMensagem1() {
		return this.mensagem1;
	}

	public void setMensagem1(String mensagem1) {
		this.mensagem1 = mensagem1;
	}

	@Column(name = "MENSAGEM2", length = 300)
	public String getMensagem2() {
		return this.mensagem2;
	}

	public void setMensagem2(String mensagem2) {
		this.mensagem2 = mensagem2;
	}

	@Column(name = "CODCLI", nullable = false, precision = 15, scale = 0)
	public long getCodcli() {
		return this.codcli;
	}

	public void setCodcli(long codcli) {
		this.codcli = codcli;
	}

	@Column(name = "VALOR", precision = 15)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "STATUS_ENVIO", precision = 3, scale = 0)
	public Short getStatusEnvio() {
		return this.statusEnvio;
	}

	public void setStatusEnvio(Short statusEnvio) {
		this.statusEnvio = statusEnvio;
	}

	@Column(name = "DETALHES")
	public Clob getDetalhes() {
		return this.detalhes;
	}

	public void setDetalhes(Clob detalhes) {
		this.detalhes = detalhes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTINCLUSAO", length = 23)
	public Date getDtinclusao() {
		return this.dtinclusao;
	}

	public void setDtinclusao(Date dtinclusao) {
		this.dtinclusao = dtinclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRINCLUSAO", length = 23)
	public Date getHrinclusao() {
		return this.hrinclusao;
	}

	public void setHrinclusao(Date hrinclusao) {
		this.hrinclusao = hrinclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTINCLUSAO_FILIAL", length = 23)
	public Date getDtinclusaoFilial() {
		return this.dtinclusaoFilial;
	}

	public void setDtinclusaoFilial(Date dtinclusaoFilial) {
		this.dtinclusaoFilial = dtinclusaoFilial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRINCLUSAO_FILIAL", length = 23)
	public Date getHrinclusaoFilial() {
		return this.hrinclusaoFilial;
	}

	public void setHrinclusaoFilial(Date hrinclusaoFilial) {
		this.hrinclusaoFilial = hrinclusaoFilial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTANALISE", length = 23)
	public Date getDtanalise() {
		return this.dtanalise;
	}

	public void setDtanalise(Date dtanalise) {
		this.dtanalise = dtanalise;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRANALISE", length = 23)
	public Date getHranalise() {
		return this.hranalise;
	}

	public void setHranalise(Date hranalise) {
		this.hranalise = hranalise;
	}

	@Column(name = "ID_PEDIDO_CARTAO", precision = 15, scale = 0)
	public Long getIdPedidoCartao() {
		return this.idPedidoCartao;
	}

	public void setIdPedidoCartao(Long idPedidoCartao) {
		this.idPedidoCartao = idPedidoCartao;
	}

	@Column(name = "NOMCLI", length = 40)
	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	@Column(name = "CGCCPF", precision = 15, scale = 0)
	public Long getCgccpf() {
		return this.cgccpf;
	}

	public void setCgccpf(Long cgccpf) {
		this.cgccpf = cgccpf;
	}

	@Column(name = "XMLLOG", length = 8000)
	public String getXmllog() {
		return this.xmllog;
	}

	public void setXmllog(String xmllog) {
		this.xmllog = xmllog;
	}

	@Column(name = "CONDPGTO", length = 3)
	public String getCondpgto() {
		return this.condpgto;
	}

	public void setCondpgto(String condpgto) {
		this.condpgto = condpgto;
	}

}
