package br.com.ziben.model;

// Generated Oct 30, 2013 4:54:18 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbAnaliseCreditoComplFncl generated by hbm2java
 */
@Entity
@Table(name = "TB_ANALISE_CREDITO_COMPL_FNCL", schema = "dbo", catalog = "dbZema")
public class TbAnaliseCreditoComplFncl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6237047181281711581L;
	
	private TbAnaliseCreditoComplFnclId id;

	public TbAnaliseCreditoComplFncl() {
	}

	public TbAnaliseCreditoComplFncl(TbAnaliseCreditoComplFnclId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codfil", column = @Column(name = "CODFIL", precision = 3, scale = 0)),
			@AttributeOverride(name = "idanalise", column = @Column(name = "IDANALISE", precision = 9, scale = 0)),
			@AttributeOverride(name = "dtultmov", column = @Column(name = "DTULTMOV", length = 23)),
			@AttributeOverride(name = "hrultmov", column = @Column(name = "HRULTMOV", length = 23)),
			@AttributeOverride(name = "creditApplicationCod", column = @Column(name = "CREDIT_APPLICATION_COD", length = 15)),
			@AttributeOverride(name = "xmllog", column = @Column(name = "XMLLOG", length = 2000)),
			@AttributeOverride(name = "mensagem1", column = @Column(name = "MENSAGEM1", length = 300)),
			@AttributeOverride(name = "mensagem2", column = @Column(name = "MENSAGEM2", length = 300)) })
	public TbAnaliseCreditoComplFnclId getId() {
		return this.id;
	}

	public void setId(TbAnaliseCreditoComplFnclId id) {
		this.id = id;
	}

}
