package br.com.ziben.model;

// Generated Nov 1, 2013 12:51:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.PersistenceUnit;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbEsteiraCredito generated by hbm2java
 */
@Entity
@PersistenceUnit(unitName = "dbFinancial")
@Table(name = "TB_ESTEIRA_CREDITO", schema = "dbo", catalog = "FINANCIAL")
public class TbEsteiraCredito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6030280415095138993L;

	private long cgccpf;
	private Short codfilUltcomp;
	private String nomcli;
	private BigDecimal vlmaiorCompra;
	private Integer qtdDiasMaiorAtraso;
	private BigDecimal vlquitado;
	private BigDecimal vlvencido;
	private BigDecimal vlvencer;
	private Integer qtdFinAberto;
	private Short qtdFinQuitado;
	private Date dtultcomp;
	private Date dtultpgto;
	private BigDecimal vlendividamentoMes;
	private Character flfunc;
	private Short qtdRenegociacao;
	private Integer qtdDiasAtraso;
	private Short maiorQtdParcelas;
	private Short qtdContratosEp;
	private Character flregistradospc;
	private Date dtultmov;
	private Date hrultmov;
	private Character flconsulta;
	private BigDecimal vlendiMesFaturado;
	private BigDecimal vlendiMesRetiranfat;
	private Character flcartaoativo;
	private Character flblacklist;

	public TbEsteiraCredito() {
	}

	public TbEsteiraCredito(long cgccpf) {
		this.cgccpf = cgccpf;
	}

	public TbEsteiraCredito(long cgccpf, Short codfilUltcomp, String nomcli, BigDecimal vlmaiorCompra, Integer qtdDiasMaiorAtraso, BigDecimal vlquitado,
			BigDecimal vlvencido, BigDecimal vlvencer, Integer qtdFinAberto, Short qtdFinQuitado, Date dtultcomp, Date dtultpgto, BigDecimal vlendividamentoMes,
			Character flfunc, Short qtdRenegociacao, Integer qtdDiasAtraso, Short maiorQtdParcelas, Short qtdContratosEp, Character flregistradospc, Date dtultmov,
			Date hrultmov, Character flconsulta, BigDecimal vlendiMesFaturado, BigDecimal vlendiMesRetiranfat, Character flcartaoativo, Character flblacklist) {
		this.cgccpf = cgccpf;
		this.codfilUltcomp = codfilUltcomp;
		this.nomcli = nomcli;
		this.vlmaiorCompra = vlmaiorCompra;
		this.qtdDiasMaiorAtraso = qtdDiasMaiorAtraso;
		this.vlquitado = vlquitado;
		this.vlvencido = vlvencido;
		this.vlvencer = vlvencer;
		this.qtdFinAberto = qtdFinAberto;
		this.qtdFinQuitado = qtdFinQuitado;
		this.dtultcomp = dtultcomp;
		this.dtultpgto = dtultpgto;
		this.vlendividamentoMes = vlendividamentoMes;
		this.flfunc = flfunc;
		this.qtdRenegociacao = qtdRenegociacao;
		this.qtdDiasAtraso = qtdDiasAtraso;
		this.maiorQtdParcelas = maiorQtdParcelas;
		this.qtdContratosEp = qtdContratosEp;
		this.flregistradospc = flregistradospc;
		this.dtultmov = dtultmov;
		this.hrultmov = hrultmov;
		this.flconsulta = flconsulta;
		this.vlendiMesFaturado = vlendiMesFaturado;
		this.vlendiMesRetiranfat = vlendiMesRetiranfat;
		this.flcartaoativo = flcartaoativo;
		this.flblacklist = flblacklist;
	}

	@Id
	@Column(name = "CGCCPF", unique = true, nullable = false, precision = 15, scale = 0)
	public long getCgccpf() {
		return this.cgccpf;
	}

	public void setCgccpf(long cgccpf) {
		this.cgccpf = cgccpf;
	}

	@Column(name = "CODFIL_ULTCOMP", precision = 3, scale = 0)
	public Short getCodfilUltcomp() {
		return this.codfilUltcomp;
	}

	public void setCodfilUltcomp(Short codfilUltcomp) {
		this.codfilUltcomp = codfilUltcomp;
	}

	@Column(name = "NOMCLI", length = 40)
	public String getNomcli() {
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	@Column(name = "VLMAIOR_COMPRA", precision = 15)
	public BigDecimal getVlmaiorCompra() {
		return this.vlmaiorCompra;
	}

	public void setVlmaiorCompra(BigDecimal vlmaiorCompra) {
		this.vlmaiorCompra = vlmaiorCompra;
	}

	@Column(name = "QTD_DIAS_MAIOR_ATRASO", precision = 6, scale = 0)
	public Integer getQtdDiasMaiorAtraso() {
		return this.qtdDiasMaiorAtraso;
	}

	public void setQtdDiasMaiorAtraso(Integer qtdDiasMaiorAtraso) {
		this.qtdDiasMaiorAtraso = qtdDiasMaiorAtraso;
	}

	@Column(name = "VLQUITADO", precision = 15)
	public BigDecimal getVlquitado() {
		return this.vlquitado;
	}

	public void setVlquitado(BigDecimal vlquitado) {
		this.vlquitado = vlquitado;
	}

	@Column(name = "VLVENCIDO", precision = 15)
	public BigDecimal getVlvencido() {
		return this.vlvencido;
	}

	public void setVlvencido(BigDecimal vlvencido) {
		this.vlvencido = vlvencido;
	}

	@Column(name = "VLVENCER", precision = 15)
	public BigDecimal getVlvencer() {
		return this.vlvencer;
	}

	public void setVlvencer(BigDecimal vlvencer) {
		this.vlvencer = vlvencer;
	}

	@Column(name = "QTD_FIN_ABERTO", precision = 6, scale = 0)
	public Integer getQtdFinAberto() {
		return this.qtdFinAberto;
	}

	public void setQtdFinAberto(Integer qtdFinAberto) {
		this.qtdFinAberto = qtdFinAberto;
	}

	@Column(name = "QTD_FIN_QUITADO", precision = 4, scale = 0)
	public Short getQtdFinQuitado() {
		return this.qtdFinQuitado;
	}

	public void setQtdFinQuitado(Short qtdFinQuitado) {
		this.qtdFinQuitado = qtdFinQuitado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTULTCOMP", length = 23)
	public Date getDtultcomp() {
		return this.dtultcomp;
	}

	public void setDtultcomp(Date dtultcomp) {
		this.dtultcomp = dtultcomp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTULTPGTO", length = 23)
	public Date getDtultpgto() {
		return this.dtultpgto;
	}

	public void setDtultpgto(Date dtultpgto) {
		this.dtultpgto = dtultpgto;
	}

	@Column(name = "VLENDIVIDAMENTO_MES", precision = 15)
	public BigDecimal getVlendividamentoMes() {
		return this.vlendividamentoMes;
	}

	public void setVlendividamentoMes(BigDecimal vlendividamentoMes) {
		this.vlendividamentoMes = vlendividamentoMes;
	}

	@Column(name = "FLFUNC", length = 1)
	public Character getFlfunc() {
		return this.flfunc;
	}

	public void setFlfunc(Character flfunc) {
		this.flfunc = flfunc;
	}

	@Column(name = "QTD_RENEGOCIACAO", precision = 4, scale = 0)
	public Short getQtdRenegociacao() {
		return this.qtdRenegociacao;
	}

	public void setQtdRenegociacao(Short qtdRenegociacao) {
		this.qtdRenegociacao = qtdRenegociacao;
	}

	@Column(name = "QTD_DIAS_ATRASO", precision = 6, scale = 0)
	public Integer getQtdDiasAtraso() {
		return this.qtdDiasAtraso;
	}

	public void setQtdDiasAtraso(Integer qtdDiasAtraso) {
		this.qtdDiasAtraso = qtdDiasAtraso;
	}

	@Column(name = "MAIOR_QTD_PARCELAS", precision = 3, scale = 0)
	public Short getMaiorQtdParcelas() {
		return this.maiorQtdParcelas;
	}

	public void setMaiorQtdParcelas(Short maiorQtdParcelas) {
		this.maiorQtdParcelas = maiorQtdParcelas;
	}

	@Column(name = "QTD_CONTRATOS_EP", precision = 3, scale = 0)
	public Short getQtdContratosEp() {
		return this.qtdContratosEp;
	}

	public void setQtdContratosEp(Short qtdContratosEp) {
		this.qtdContratosEp = qtdContratosEp;
	}

	@Column(name = "FLREGISTRADOSPC", length = 1)
	public Character getFlregistradospc() {
		return this.flregistradospc;
	}

	public void setFlregistradospc(Character flregistradospc) {
		this.flregistradospc = flregistradospc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTULTMOV", length = 23)
	public Date getDtultmov() {
		return this.dtultmov;
	}

	public void setDtultmov(Date dtultmov) {
		this.dtultmov = dtultmov;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HRULTMOV", length = 23)
	public Date getHrultmov() {
		return this.hrultmov;
	}

	public void setHrultmov(Date hrultmov) {
		this.hrultmov = hrultmov;
	}

	@Column(name = "FLCONSULTA", length = 1)
	public Character getFlconsulta() {
		return this.flconsulta;
	}

	public void setFlconsulta(Character flconsulta) {
		this.flconsulta = flconsulta;
	}

	@Column(name = "VLENDI_MES_FATURADO", precision = 15)
	public BigDecimal getVlendiMesFaturado() {
		return this.vlendiMesFaturado;
	}

	public void setVlendiMesFaturado(BigDecimal vlendiMesFaturado) {
		this.vlendiMesFaturado = vlendiMesFaturado;
	}

	@Column(name = "VLENDI_MES_RETIRANFAT", precision = 15)
	public BigDecimal getVlendiMesRetiranfat() {
		return this.vlendiMesRetiranfat;
	}

	public void setVlendiMesRetiranfat(BigDecimal vlendiMesRetiranfat) {
		this.vlendiMesRetiranfat = vlendiMesRetiranfat;
	}

	@Column(name = "FLCARTAOATIVO", length = 1)
	public Character getFlcartaoativo() {
		return this.flcartaoativo;
	}

	public void setFlcartaoativo(Character flcartaoativo) {
		this.flcartaoativo = flcartaoativo;
	}

	@Column(name = "FLBLACKLIST", length = 1)
	public Character getFlblacklist() {
		return this.flblacklist;
	}

	public void setFlblacklist(Character flblacklist) {
		this.flblacklist = flblacklist;
	}

}
