package br.com.ziben.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-29T20:29:16.799-02:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://gestorvarejo.toolssoftware.com/wsdl/", name = "FinancialService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FinancialService {

	@WebResult(name = "ProcessOutputMessageResponse", targetNamespace = "http://gestorvarejo.toolssoftware.com/wsdl/", partName = "ProcessOutputMessageResponse")
	@WebMethod(operationName = "ProcessOutputMessage", action = "http://gestorvarejo.toolssoftware.com/wsdl/ProcessOutputMessage")
	public java.lang.String processOutputMessage(
			@WebParam(partName = "ProcessOutputMessageRequest", name = "ProcessOutputMessageRequest") java.lang.String processOutputMessageRequest);
}
