package br.com.ziben.services;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-29T20:29:16.835-02:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "FinancialService", wsdlLocation = "http://172.30.0.58/gestor-varejo/services/RetailProposalRegister?wsdl", targetNamespace = "http://gestorvarejo.toolssoftware.com/wsdl/")
public class FinancialService_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://gestorvarejo.toolssoftware.com/wsdl/", "FinancialService");
	public final static QName ProcessOutputMessage = new QName("http://gestorvarejo.toolssoftware.com/wsdl/", "ProcessOutputMessage");
	static {
		URL url = null;
		try {
			url = new URL("http://172.30.0.58/gestor-varejo/services/RetailProposalRegister?wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(FinancialService_Service.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "http://172.30.0.58/gestor-varejo/services/RetailProposalRegister?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public FinancialService_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public FinancialService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FinancialService_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return
	 *         returns FinancialService
	 */
	@WebEndpoint(name = "ProcessOutputMessage")
	public FinancialService getProcessOutputMessage() {
		return super.getPort(ProcessOutputMessage, FinancialService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have
	 *            their default values.
	 * @return
	 *         returns FinancialService
	 */
	@WebEndpoint(name = "ProcessOutputMessage")
	public FinancialService getProcessOutputMessage(WebServiceFeature... features) {
		return super.getPort(ProcessOutputMessage, FinancialService.class, features);
	}

}
