package br.com.ziben.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-29T20:29:16.790-02:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://gestorvarejo.toolssoftware.com/wsdl/", name = "ReturnAnalysisStatus")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ReturnAnalysisStatus {

	@WebResult(name = "ReturnAnalysisStatusResponse", targetNamespace = "http://gestorvarejo.toolssoftware.com/wsdl/", partName = "ReturnAnalysisStatusResponse")
	@WebMethod(operationName = "ReturnAnalysisStatus", action = "http://gestorvarejo.toolssoftware.com/wsdl/ReturnAnalysisStatus")
	public java.lang.String returnAnalysisStatus(
			@WebParam(partName = "ReturnAnalysisStatusRequest", name = "ReturnAnalysisStatusRequest") java.lang.String returnAnalysisStatusRequest);
}
