/**
	This file is part of adapt-through.

    Adapt-through is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Adapt-through is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Adapt-through.  If not, see <http://www.gnu.org/licenses/>.
 */

package br.com.ziben.services;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-29T20:29:16.815-02:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ReturnAnalysisStatus", wsdlLocation = "http://172.30.0.58/gestor-varejo/services/RetailProposalRegister?wsdl", targetNamespace = "http://gestorvarejo.toolssoftware.com/wsdl/")
public class ReturnAnalysisStatus_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://gestorvarejo.toolssoftware.com/wsdl/", "ReturnAnalysisStatus");
	public final static QName ReturnAnalysisStatus = new QName("http://gestorvarejo.toolssoftware.com/wsdl/", "ReturnAnalysisStatus");
	static {
		URL url = null;
		try {
			url = new URL("http://172.30.0.58/gestor-varejo/services/RetailProposalRegister?wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(ReturnAnalysisStatus_Service.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "http://172.30.0.58/gestor-varejo/services/RetailProposalRegister?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public ReturnAnalysisStatus_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ReturnAnalysisStatus_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ReturnAnalysisStatus_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return
	 *         returns ReturnAnalysisStatus
	 */
	@WebEndpoint(name = "ReturnAnalysisStatus")
	public ReturnAnalysisStatus getReturnAnalysisStatus() {
		return super.getPort(ReturnAnalysisStatus, ReturnAnalysisStatus.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have
	 *            their default values.
	 * @return
	 *         returns ReturnAnalysisStatus
	 */
	@WebEndpoint(name = "ReturnAnalysisStatus")
	public ReturnAnalysisStatus getReturnAnalysisStatus(WebServiceFeature... features) {
		return super.getPort(ReturnAnalysisStatus, ReturnAnalysisStatus.class, features);
	}

}
